# Generated by Django 5.1.3 on 2024-12-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_list.news')),
            ],
        ),
    ]
